// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALeCZ4aFEvNc307BtJHcQYqSgW63ITkA4',
    appId: '1:193073537350:web:6ab1c20ad6141a26664547',
    messagingSenderId: '193073537350',
    projectId: 'flutter-login-app-33ed4',
    authDomain: 'flutter-login-app-33ed4.firebaseapp.com',
    storageBucket: 'flutter-login-app-33ed4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXMjYLucfFyJlxqu1AlneFiIiF_FzCWZY',
    appId: '1:193073537350:android:d6dbb6a338caf6c3664547',
    messagingSenderId: '193073537350',
    projectId: 'flutter-login-app-33ed4',
    storageBucket: 'flutter-login-app-33ed4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC7FODj34DrxuAKyIcORFuLPB4HV5Y7Uw',
    appId: '1:193073537350:ios:83e7e7fce98a170b664547',
    messagingSenderId: '193073537350',
    projectId: 'flutter-login-app-33ed4',
    storageBucket: 'flutter-login-app-33ed4.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC7FODj34DrxuAKyIcORFuLPB4HV5Y7Uw',
    appId: '1:193073537350:ios:83e7e7fce98a170b664547',
    messagingSenderId: '193073537350',
    projectId: 'flutter-login-app-33ed4',
    storageBucket: 'flutter-login-app-33ed4.appspot.com',
    iosBundleId: 'com.example.project',
  );
}
